#ifndef CHESS_GAME_STATES_CHESSSTATE_H_
#define CHESS_GAME_STATES_CHESSSTATE_H_

enum ChessState {
    HUMAN_SELECT_PIECE, HUMAN_PIECE_SELECTED, COMPUTER_MOVE, NO_OP,
};

#endif /* CHESS_GAME_STATES_CHESSSTATE_H_ */
