#ifndef CHESS_GAME_STATES_CHESSSTATE_H_
#define CHESS_GAME_STATES_CHESSSTATE_H_

enum ChessState {
	WHITE_PLAYER,
	WHITE_SELECT_PIECE,
	WHITE_PIECE_SELECTED,
	FINISH_WHITE_MOVE,
	COMPUTER_MOVE,
	NO_OP,
};

#endif /* CHESS_GAME_STATES_CHESSSTATE_H_ */
