/*
 * ChessState.h
 *
 *  Created on: Jan 9, 2022
 *      Author: ubuntu
 */

#ifndef CHESS_GAME_STATES_CHESSSTATE_H_
#define CHESS_GAME_STATES_CHESSSTATE_H_


enum ChessState {
	WHITE_PLAYER_HUMAN_MOVE,
	HUMAN_SELECT_PIECE,
	HUMAN_PIECE_SELECTED,
	FINISH_HUMAN_MOVE,
	COMPUTER_MOVE,
	NO_OP,
};


#endif /* CHESS_GAME_STATES_CHESSSTATE_H_ */
