/*
 * GameObjects.h
 *
 *  Created on: Jan 8, 2022
 *      Author: ubuntu
 */

#ifndef CHESS_GAME_ENUMS_CHESSASSETS_H_
#define CHESS_GAME_ENUMS_CHESSASSETS_H_

enum ChessAssets {
	START_SCREEN_BACKGROUND_IMAGE,
	NEW_GAME_BUTTON,
	BOARD,
	WHITE_ROOK_ON_BLACK,
	WHITE_KNIGHT_ON_WHITE,
	WHITE_BISHOP_ON_BLACK,
	WHITE_QUEEN,
	WHITE_KING,
	WHITE_ROOK_ON_WHITE,
	WHITE_KNIGHT_ON_BLACK,
	WHITE_BISHOP_ON_WHITE,
	WHITE_PAWN_1,
	WHITE_PAWN_2,
	WHITE_PAWN_3,
	WHITE_PAWN_4,
	WHITE_PAWN_5,
	WHITE_PAWN_6,
	WHITE_PAWN_7,
	WHITE_PAWN_8,

	BLACK_ROOK_ON_BLACK,
	BLACK_KNIGHT_ON_WHITE,
	BLACK_BISHOP_ON_BLACK,
	BLACK_QUEEN,
	BLACK_KING,
	BLACK_ROOK_ON_WHITE,
	BLACK_KNIGHT_ON_BLACK,
	BLACK_BISHOP_ON_WHITE,
	BLACK_PAWN_1,
	BLACK_PAWN_2,
	BLACK_PAWN_3,
	BLACK_PAWN_4,
	BLACK_PAWN_5,
	BLACK_PAWN_6,
	BLACK_PAWN_7,
	BLACK_PAWN_8,
};

#endif /* CHESS_GAME_ENUMS_CHESSASSETS_H_ */
